#! /bin/bash
docker --version
echo "Building branch ${LEMUR_VERSION:=master} from repo ${LEMUR_REPO:=netflix/lemur} with make ${LEMUR_TARGET:=develop}"
# shellcheck disable=SC2086
# SC2086 doesn't properly handle the default values
docker build --build-arg LEMUR_VERSION=${LEMUR_VERSION:-master} --build-arg LEMUR_TARGET=${LEMUR_TARGET:-develop} --build-arg LEMUR_REPO=${LEMUR_REPO:-netflix/lemur} -t $IMAGE_NAME -f $DOCKERFILE_PATH  .
