#! /bin/bash
docker --version
echo "Building branch ${LEMUR_VERSION:=master} from repo ${LEMUR_REPO:=netflix/lemur} for image $IMAGE_NAME from dockerfile $DOCKERFILE_PATH"
# shellcheck disable=SC2086
# SC2086 doesn't properly handle the default values
docker build --build-arg LEMUR_VERSION=${LEMUR_VERSION:-master} --build-arg LEMUR_REPO=${LEMUR_REPO:-netflix/lemur} -t $IMAGE_NAME -f $DOCKERFILE_PATH .
